### ISSUE TITLE
philip-adminduty

### ISSUE THREAD

**Issue by ivegotthis** [TN-DEVV/TN-adminmenu#1]
Hi, i have this issue:

MainThrd/ Error parsing script @philip-adminduty/config.lua in resource philip-adminduty: @philip-adminduty/config.lua:10: '}' expected (to close '{' at line 1) near 'clothes'

And i haven't changed anything.
Thanks.

**Comment by TN-SCRIPTS** [comment]
I fixed the error
Please join our discord to have a better support and discover our releases
https://discord.gg/qnpG6TmsaV

Le lun. 18 sept. 2023, 02 h 59, ivegotthis ***@***.***> a
écrit :

**Comment by ivegotthis** [comment]
Thanks
